[workspace]
members = [
        "day01",
        "day02",
        "day03",
        "day04",
        "day05",
        "day06",
        "intcode",
        "day02new",
        "day05new",
        "day07"
    ]
