[package]
name = "aoc"
version = "0.1.0"
authors = ["Mark J Musante <mark.musante@oracle.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
